name: sparsemodels_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - numpy==1.25.2
  - libxcrypt
  - pip
  - r-base
  - r-essentials
  - r-rgcca
  - pip:
    - cython
    - rpy2
    - tqdm

